//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://KnockKnock.readify.net", ClrNamespace = "knockknock.readify.net")]

namespace knockknock.readify.net
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ContactDetails", Namespace = "http://KnockKnock.readify.net")]
    public partial class ContactDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string EmailAddressField;

        private string FamilyNameField;

        private string GivenNameField;

        private string PhoneNumberField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FamilyName
        {
            get
            {
                return this.FamilyNameField;
            }
            set
            {
                this.FamilyNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GivenName
        {
            get
            {
                return this.GivenNameField;
            }
            set
            {
                this.GivenNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TriangleType", Namespace = "http://KnockKnock.readify.net")]
    public enum TriangleType : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Equilateral = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Isosceles = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Scalene = 3,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://KnockKnock.readify.net", ConfigurationName = "IRedPill")]
public interface IRedPill
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://KnockKnock.readify.net/IRedPill/WhoAreYou", ReplyAction = "http://KnockKnock.readify.net/IRedPill/WhoAreYouResponse")]
    knockknock.readify.net.ContactDetails WhoAreYou();

    [System.ServiceModel.OperationContractAttribute(Action = "http://KnockKnock.readify.net/IRedPill/WhoAreYou", ReplyAction = "http://KnockKnock.readify.net/IRedPill/WhoAreYouResponse")]
    System.Threading.Tasks.Task<knockknock.readify.net.ContactDetails> WhoAreYouAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://KnockKnock.readify.net/IRedPill/FibonacciNumber", ReplyAction = "http://KnockKnock.readify.net/IRedPill/FibonacciNumberResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentOutOfRangeException), Action = "http://KnockKnock.readify.net/IRedPill/FibonacciNumberArgumentOutOfRangeException" +
        "Fault", Name = "ArgumentOutOfRangeException", Namespace = "http://schemas.datacontract.org/2004/07/System")]
    long FibonacciNumber(long n);

    [System.ServiceModel.OperationContractAttribute(Action = "http://KnockKnock.readify.net/IRedPill/FibonacciNumber", ReplyAction = "http://KnockKnock.readify.net/IRedPill/FibonacciNumberResponse")]
    System.Threading.Tasks.Task<long> FibonacciNumberAsync(long n);

    [System.ServiceModel.OperationContractAttribute(Action = "http://KnockKnock.readify.net/IRedPill/WhatShapeIsThis", ReplyAction = "http://KnockKnock.readify.net/IRedPill/WhatShapeIsThisResponse")]
    knockknock.readify.net.TriangleType WhatShapeIsThis(int a, int b, int c);

    [System.ServiceModel.OperationContractAttribute(Action = "http://KnockKnock.readify.net/IRedPill/WhatShapeIsThis", ReplyAction = "http://KnockKnock.readify.net/IRedPill/WhatShapeIsThisResponse")]
    System.Threading.Tasks.Task<knockknock.readify.net.TriangleType> WhatShapeIsThisAsync(int a, int b, int c);

    [System.ServiceModel.OperationContractAttribute(Action = "http://KnockKnock.readify.net/IRedPill/ReverseWords", ReplyAction = "http://KnockKnock.readify.net/IRedPill/ReverseWordsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentNullException), Action = "http://KnockKnock.readify.net/IRedPill/ReverseWordsArgumentNullExceptionFault", Name = "ArgumentNullException", Namespace = "http://schemas.datacontract.org/2004/07/System")]
    string ReverseWords(string s);

    [System.ServiceModel.OperationContractAttribute(Action = "http://KnockKnock.readify.net/IRedPill/ReverseWords", ReplyAction = "http://KnockKnock.readify.net/IRedPill/ReverseWordsResponse")]
    System.Threading.Tasks.Task<string> ReverseWordsAsync(string s);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRedPillChannel : IRedPill, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RedPillClient : System.ServiceModel.ClientBase<IRedPill>, IRedPill
{

    public RedPillClient()
    {
    }

    public RedPillClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public RedPillClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public RedPillClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public RedPillClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public knockknock.readify.net.ContactDetails WhoAreYou()
    {
        return base.Channel.WhoAreYou();
    }

    public System.Threading.Tasks.Task<knockknock.readify.net.ContactDetails> WhoAreYouAsync()
    {
        return base.Channel.WhoAreYouAsync();
    }

    public long FibonacciNumber(long n)
    {
        return base.Channel.FibonacciNumber(n);
    }

    public System.Threading.Tasks.Task<long> FibonacciNumberAsync(long n)
    {
        return base.Channel.FibonacciNumberAsync(n);
    }

    public knockknock.readify.net.TriangleType WhatShapeIsThis(int a, int b, int c)
    {
        return base.Channel.WhatShapeIsThis(a, b, c);
    }

    public System.Threading.Tasks.Task<knockknock.readify.net.TriangleType> WhatShapeIsThisAsync(int a, int b, int c)
    {
        return base.Channel.WhatShapeIsThisAsync(a, b, c);
    }

    public string ReverseWords(string s)
    {
        return base.Channel.ReverseWords(s);
    }

    public System.Threading.Tasks.Task<string> ReverseWordsAsync(string s)
    {
        return base.Channel.ReverseWordsAsync(s);
    }
}
