//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IRedPill", Namespace="http://tempuri.org/")]
public partial class BasicHttpBinding_IRedPill : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback WhatIsYourTokenOperationCompleted;
    
    private System.Threading.SendOrPostCallback FibonacciNumberOperationCompleted;
    
    private System.Threading.SendOrPostCallback WhatShapeIsThisOperationCompleted;
    
    private System.Threading.SendOrPostCallback ReverseWordsOperationCompleted;
    
    /// <remarks/>
    public BasicHttpBinding_IRedPill() {
        //this.Url = "http://knockknock.readify.net/RedPill.svc";
        //this.Url = "http://readifyredpillservice.azurewebsites.net/RedPillService.svc";
        this.Url = "http://localhost:50929/RedPillService.svc";
    }
    
    /// <remarks/>
    public event WhatIsYourTokenCompletedEventHandler WhatIsYourTokenCompleted;
    
    /// <remarks/>
    public event FibonacciNumberCompletedEventHandler FibonacciNumberCompleted;
    
    /// <remarks/>
    public event WhatShapeIsThisCompletedEventHandler WhatShapeIsThisCompleted;
    
    /// <remarks/>
    public event ReverseWordsCompletedEventHandler ReverseWordsCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://KnockKnock.readify.net/IRedPill/WhatIsYourToken", RequestNamespace="http://KnockKnock.readify.net", ResponseNamespace="http://KnockKnock.readify.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string WhatIsYourToken() {
        object[] results = this.Invoke("WhatIsYourToken", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginWhatIsYourToken(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("WhatIsYourToken", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndWhatIsYourToken(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void WhatIsYourTokenAsync() {
        this.WhatIsYourTokenAsync(null);
    }
    
    /// <remarks/>
    public void WhatIsYourTokenAsync(object userState) {
        if ((this.WhatIsYourTokenOperationCompleted == null)) {
            this.WhatIsYourTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWhatIsYourTokenOperationCompleted);
        }
        this.InvokeAsync("WhatIsYourToken", new object[0], this.WhatIsYourTokenOperationCompleted, userState);
    }
    
    private void OnWhatIsYourTokenOperationCompleted(object arg) {
        if ((this.WhatIsYourTokenCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.WhatIsYourTokenCompleted(this, new WhatIsYourTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://KnockKnock.readify.net/IRedPill/FibonacciNumber", RequestNamespace="http://KnockKnock.readify.net", ResponseNamespace="http://KnockKnock.readify.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void FibonacciNumber(long n, [System.Xml.Serialization.XmlIgnoreAttribute()] bool nSpecified, out long FibonacciNumberResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool FibonacciNumberResultSpecified) {
        object[] results = this.Invoke("FibonacciNumber", new object[] {
                    n,
                    nSpecified});
        FibonacciNumberResult = ((long)(results[0]));
        FibonacciNumberResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginFibonacciNumber(long n, bool nSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("FibonacciNumber", new object[] {
                    n,
                    nSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndFibonacciNumber(System.IAsyncResult asyncResult, out long FibonacciNumberResult, out bool FibonacciNumberResultSpecified) {
        object[] results = this.EndInvoke(asyncResult);
        FibonacciNumberResult = ((long)(results[0]));
        FibonacciNumberResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public void FibonacciNumberAsync(long n, bool nSpecified) {
        this.FibonacciNumberAsync(n, nSpecified, null);
    }
    
    /// <remarks/>
    public void FibonacciNumberAsync(long n, bool nSpecified, object userState) {
        if ((this.FibonacciNumberOperationCompleted == null)) {
            this.FibonacciNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFibonacciNumberOperationCompleted);
        }
        this.InvokeAsync("FibonacciNumber", new object[] {
                    n,
                    nSpecified}, this.FibonacciNumberOperationCompleted, userState);
    }
    
    private void OnFibonacciNumberOperationCompleted(object arg) {
        if ((this.FibonacciNumberCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.FibonacciNumberCompleted(this, new FibonacciNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://KnockKnock.readify.net/IRedPill/WhatShapeIsThis", RequestNamespace="http://KnockKnock.readify.net", ResponseNamespace="http://KnockKnock.readify.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void WhatShapeIsThis(int a, [System.Xml.Serialization.XmlIgnoreAttribute()] bool aSpecified, int b, [System.Xml.Serialization.XmlIgnoreAttribute()] bool bSpecified, int c, [System.Xml.Serialization.XmlIgnoreAttribute()] bool cSpecified, out TriangleType WhatShapeIsThisResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool WhatShapeIsThisResultSpecified) {
        object[] results = this.Invoke("WhatShapeIsThis", new object[] {
                    a,
                    aSpecified,
                    b,
                    bSpecified,
                    c,
                    cSpecified});
        WhatShapeIsThisResult = ((TriangleType)(results[0]));
        WhatShapeIsThisResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginWhatShapeIsThis(int a, bool aSpecified, int b, bool bSpecified, int c, bool cSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("WhatShapeIsThis", new object[] {
                    a,
                    aSpecified,
                    b,
                    bSpecified,
                    c,
                    cSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndWhatShapeIsThis(System.IAsyncResult asyncResult, out TriangleType WhatShapeIsThisResult, out bool WhatShapeIsThisResultSpecified) {
        object[] results = this.EndInvoke(asyncResult);
        WhatShapeIsThisResult = ((TriangleType)(results[0]));
        WhatShapeIsThisResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public void WhatShapeIsThisAsync(int a, bool aSpecified, int b, bool bSpecified, int c, bool cSpecified) {
        this.WhatShapeIsThisAsync(a, aSpecified, b, bSpecified, c, cSpecified, null);
    }
    
    /// <remarks/>
    public void WhatShapeIsThisAsync(int a, bool aSpecified, int b, bool bSpecified, int c, bool cSpecified, object userState) {
        if ((this.WhatShapeIsThisOperationCompleted == null)) {
            this.WhatShapeIsThisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWhatShapeIsThisOperationCompleted);
        }
        this.InvokeAsync("WhatShapeIsThis", new object[] {
                    a,
                    aSpecified,
                    b,
                    bSpecified,
                    c,
                    cSpecified}, this.WhatShapeIsThisOperationCompleted, userState);
    }
    
    private void OnWhatShapeIsThisOperationCompleted(object arg) {
        if ((this.WhatShapeIsThisCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.WhatShapeIsThisCompleted(this, new WhatShapeIsThisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://KnockKnock.readify.net/IRedPill/ReverseWords", RequestNamespace="http://KnockKnock.readify.net", ResponseNamespace="http://KnockKnock.readify.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ReverseWords([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string s) {
        object[] results = this.Invoke("ReverseWords", new object[] {
                    s});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginReverseWords(string s, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ReverseWords", new object[] {
                    s}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndReverseWords(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ReverseWordsAsync(string s) {
        this.ReverseWordsAsync(s, null);
    }
    
    /// <remarks/>
    public void ReverseWordsAsync(string s, object userState) {
        if ((this.ReverseWordsOperationCompleted == null)) {
            this.ReverseWordsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReverseWordsOperationCompleted);
        }
        this.InvokeAsync("ReverseWords", new object[] {
                    s}, this.ReverseWordsOperationCompleted, userState);
    }
    
    private void OnReverseWordsOperationCompleted(object arg) {
        if ((this.ReverseWordsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ReverseWordsCompleted(this, new ReverseWordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
// CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpsBinding_IRedPill", Namespace="http://tempuri.org/")]
public partial class BasicHttpsBinding_IRedPill : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback WhatIsYourTokenOperationCompleted;
    
    private System.Threading.SendOrPostCallback FibonacciNumberOperationCompleted;
    
    private System.Threading.SendOrPostCallback WhatShapeIsThisOperationCompleted;
    
    private System.Threading.SendOrPostCallback ReverseWordsOperationCompleted;
    
    /// <remarks/>
    public BasicHttpsBinding_IRedPill() {
        this.Url = "https://knockknock.azurewebsites.net/RedPill.svc";
    }
    
    /// <remarks/>
    public event WhatIsYourTokenCompletedEventHandler WhatIsYourTokenCompleted;
    
    /// <remarks/>
    public event FibonacciNumberCompletedEventHandler FibonacciNumberCompleted;
    
    /// <remarks/>
    public event WhatShapeIsThisCompletedEventHandler WhatShapeIsThisCompleted;
    
    /// <remarks/>
    public event ReverseWordsCompletedEventHandler ReverseWordsCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://KnockKnock.readify.net/IRedPill/WhatIsYourToken", RequestNamespace="http://KnockKnock.readify.net", ResponseNamespace="http://KnockKnock.readify.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string WhatIsYourToken() {
        object[] results = this.Invoke("WhatIsYourToken", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginWhatIsYourToken(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("WhatIsYourToken", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndWhatIsYourToken(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void WhatIsYourTokenAsync() {
        this.WhatIsYourTokenAsync(null);
    }
    
    /// <remarks/>
    public void WhatIsYourTokenAsync(object userState) {
        if ((this.WhatIsYourTokenOperationCompleted == null)) {
            this.WhatIsYourTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWhatIsYourTokenOperationCompleted);
        }
        this.InvokeAsync("WhatIsYourToken", new object[0], this.WhatIsYourTokenOperationCompleted, userState);
    }
    
    private void OnWhatIsYourTokenOperationCompleted(object arg) {
        if ((this.WhatIsYourTokenCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.WhatIsYourTokenCompleted(this, new WhatIsYourTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://KnockKnock.readify.net/IRedPill/FibonacciNumber", RequestNamespace="http://KnockKnock.readify.net", ResponseNamespace="http://KnockKnock.readify.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void FibonacciNumber(long n, [System.Xml.Serialization.XmlIgnoreAttribute()] bool nSpecified, out long FibonacciNumberResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool FibonacciNumberResultSpecified) {
        object[] results = this.Invoke("FibonacciNumber", new object[] {
                    n,
                    nSpecified});
        FibonacciNumberResult = ((long)(results[0]));
        FibonacciNumberResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginFibonacciNumber(long n, bool nSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("FibonacciNumber", new object[] {
                    n,
                    nSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndFibonacciNumber(System.IAsyncResult asyncResult, out long FibonacciNumberResult, out bool FibonacciNumberResultSpecified) {
        object[] results = this.EndInvoke(asyncResult);
        FibonacciNumberResult = ((long)(results[0]));
        FibonacciNumberResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public void FibonacciNumberAsync(long n, bool nSpecified) {
        this.FibonacciNumberAsync(n, nSpecified, null);
    }
    
    /// <remarks/>
    public void FibonacciNumberAsync(long n, bool nSpecified, object userState) {
        if ((this.FibonacciNumberOperationCompleted == null)) {
            this.FibonacciNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFibonacciNumberOperationCompleted);
        }
        this.InvokeAsync("FibonacciNumber", new object[] {
                    n,
                    nSpecified}, this.FibonacciNumberOperationCompleted, userState);
    }
    
    private void OnFibonacciNumberOperationCompleted(object arg) {
        if ((this.FibonacciNumberCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.FibonacciNumberCompleted(this, new FibonacciNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://KnockKnock.readify.net/IRedPill/WhatShapeIsThis", RequestNamespace="http://KnockKnock.readify.net", ResponseNamespace="http://KnockKnock.readify.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void WhatShapeIsThis(int a, [System.Xml.Serialization.XmlIgnoreAttribute()] bool aSpecified, int b, [System.Xml.Serialization.XmlIgnoreAttribute()] bool bSpecified, int c, [System.Xml.Serialization.XmlIgnoreAttribute()] bool cSpecified, out TriangleType WhatShapeIsThisResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool WhatShapeIsThisResultSpecified) {
        object[] results = this.Invoke("WhatShapeIsThis", new object[] {
                    a,
                    aSpecified,
                    b,
                    bSpecified,
                    c,
                    cSpecified});
        WhatShapeIsThisResult = ((TriangleType)(results[0]));
        WhatShapeIsThisResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginWhatShapeIsThis(int a, bool aSpecified, int b, bool bSpecified, int c, bool cSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("WhatShapeIsThis", new object[] {
                    a,
                    aSpecified,
                    b,
                    bSpecified,
                    c,
                    cSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndWhatShapeIsThis(System.IAsyncResult asyncResult, out TriangleType WhatShapeIsThisResult, out bool WhatShapeIsThisResultSpecified) {
        object[] results = this.EndInvoke(asyncResult);
        WhatShapeIsThisResult = ((TriangleType)(results[0]));
        WhatShapeIsThisResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public void WhatShapeIsThisAsync(int a, bool aSpecified, int b, bool bSpecified, int c, bool cSpecified) {
        this.WhatShapeIsThisAsync(a, aSpecified, b, bSpecified, c, cSpecified, null);
    }
    
    /// <remarks/>
    public void WhatShapeIsThisAsync(int a, bool aSpecified, int b, bool bSpecified, int c, bool cSpecified, object userState) {
        if ((this.WhatShapeIsThisOperationCompleted == null)) {
            this.WhatShapeIsThisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWhatShapeIsThisOperationCompleted);
        }
        this.InvokeAsync("WhatShapeIsThis", new object[] {
                    a,
                    aSpecified,
                    b,
                    bSpecified,
                    c,
                    cSpecified}, this.WhatShapeIsThisOperationCompleted, userState);
    }
    
    private void OnWhatShapeIsThisOperationCompleted(object arg) {
        if ((this.WhatShapeIsThisCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.WhatShapeIsThisCompleted(this, new WhatShapeIsThisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://KnockKnock.readify.net/IRedPill/ReverseWords", RequestNamespace="http://KnockKnock.readify.net", ResponseNamespace="http://KnockKnock.readify.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ReverseWords([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string s) {
        object[] results = this.Invoke("ReverseWords", new object[] {
                    s});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginReverseWords(string s, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ReverseWords", new object[] {
                    s}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndReverseWords(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ReverseWordsAsync(string s) {
        this.ReverseWordsAsync(s, null);
    }
    
    /// <remarks/>
    public void ReverseWordsAsync(string s, object userState) {
        if ((this.ReverseWordsOperationCompleted == null)) {
            this.ReverseWordsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReverseWordsOperationCompleted);
        }
        this.InvokeAsync("ReverseWords", new object[] {
                    s}, this.ReverseWordsOperationCompleted, userState);
    }
    
    private void OnReverseWordsOperationCompleted(object arg) {
        if ((this.ReverseWordsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ReverseWordsCompleted(this, new ReverseWordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://KnockKnock.readify.net")]
public enum TriangleType {
    
    /// <remarks/>
    Error,
    
    /// <remarks/>
    Equilateral,
    
    /// <remarks/>
    Isosceles,
    
    /// <remarks/>
    Scalene,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void WhatIsYourTokenCompletedEventHandler(object sender, WhatIsYourTokenCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class WhatIsYourTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal WhatIsYourTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void FibonacciNumberCompletedEventHandler(object sender, FibonacciNumberCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class FibonacciNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal FibonacciNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public long FibonacciNumberResult {
        get {
            this.RaiseExceptionIfNecessary();
            return ((long)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public bool FibonacciNumberResultSpecified {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void WhatShapeIsThisCompletedEventHandler(object sender, WhatShapeIsThisCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class WhatShapeIsThisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal WhatShapeIsThisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public TriangleType WhatShapeIsThisResult {
        get {
            this.RaiseExceptionIfNecessary();
            return ((TriangleType)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public bool WhatShapeIsThisResultSpecified {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void ReverseWordsCompletedEventHandler(object sender, ReverseWordsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ReverseWordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ReverseWordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
